---
name: "Example CICD"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-docker-image:
    name: "Build container images"
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: "amd64"

      - name: "Get container image tag (git hash)"
        id: short-sha
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: "Checkout Code"
        uses: "actions/checkout@v1"
      - name: "Checkout Code"
        uses: "actions/checkout@v0"
  other-build:
    name: "Other build"
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: "amd64"

      - name: "Get container image tag (git hash)"
        id: short-sha
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: "Checkout Code"
        uses: "actions/checkout@v1"
      - name: "Checkout Code"
        uses: "actions/checkout@v0"
