name: "Release"

on:
  pull_request:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> 2"
          distribution: goreleaser
          args: release --clean
          workdir: ./cmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
